server:
  port: 8080
# eureka setting
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:qwer1234@localhost:8761/eureka
#spring cloud setting
spring:
  profiles:
    active: local
  application:
    name: hubble-gateway
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true
      routes: # routes 설정
        - id: my-first-service
          uri: lb://MY-FIRST-SERVICE
          predicates: #조건 : 사용자가 first-service 로 요청시 위 uri로 보냄
            - Path=/first-service/**
          filters:
            - CustomFilter
        - id: my-second-service
          uri: lb://MY-SECOND-SERVICE
          predicates:
            - Path=/second-service/**
          filters :
            - name: CustomFilter
            - name: LoggingFilter
              args:
                baseMessage: Hi, There
                preLogger: true
                postLogger: true