server:
  port: 8082
spring:
  application:
    name: my-second-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true # 외부에서 검색
    service-url:
      defaultZone: http://admin:qwer1234@127.0.0.1:8761/eureka
